#!/usr/bin/python3
import os
import sys

#VARS
extrastuff = "";
extralib = "";
selectname = "";
moretoimport = 1;

nbOfArgs = (sys.argv)

if len(nbOfArgs) <= 1:
  print("\nPlease enter at least 1 c program to compile\n")
  sys.exit();


word1 = sys.argv[1]
os.system("clear")
print("we will compile your source code called -->\t " + word1[:-2])

 #   #new name
 #   uwant2name = input("Name the program other than   " + word1[:-2] + " : y/n  ")
 #
 #   if uwant2name == "y":
 #     selectname = input("Type the new name : \t\t\t")
 #     extrastuff += " -o " + selectname
 #   else:
 #     extrastuff += " -o " + word1[:-2]
  
extrastuff += " -o " + word1[:-2]


#EXTRA LIB
uwantextra = input("Extra Stuff : y/n [n]? \t\t")
if uwantextra == "y":
  while moretoimport == 1:
    if uwantextra == "y" or uwantextra == "":
      print("\nWhat are we adding ? \t\t ")
      extralib = input(" 1 -lncurses \n 2 -lform \n:")

    if extralib == "1":
      extrastuff += " -lncurses"
    if extralib == "2":
      extrastuff += " -lform"


    more = input("put more stuff ? y/n [n]")
    if more == "n" or more == "":
      moretoimport = 0

  ## collect2 ld 1 = no -lncurses
  ##
  
print("\n\nIf you want to do the compiling by youself use this  : " + "\ngcc " + word1 + extrastuff)
print("\n\n\n")
#GO
if extrastuff == "":
  os.system("gcc " + word1)
else:
  os.system("gcc " + word1 + extrastuff)
